truncate table UserLedgerAccnt
truncate table UserOrganization
truncate table AppAccessRoleMap
truncate table AppAccess
truncate table AppMenuMaster
truncate table CodesDetail
truncate table CodesMaster
truncate table CostCenters
truncate table CurrencyMaster
truncate table EmbassyMaster
truncate table Organization
truncate table PettyCashAccount
truncate table PettyCashTeller
truncate table PettyCashTransfer
truncate table SystemSettings
truncate table UserMaster
truncate table UserRole
truncate table UserRoleMap
truncate table UserSetting
truncate table VendorMaster
truncate table LedgerAccounts
truncate table LedgerAccountGrps
truncate table LangMaster
